enum ActionTypes {
  LIST_DESCRIPTIONS_REQUEST = "LIST_DESCRIPTIONS_REQUEST",
  LIST_DESCRIPTIONS_RESPONSE = "LIST_DESCRIPTIONS_RESPONSE",
  ADD_DESCRIPTIONS_REQUEST = "ADD_DESCRIPTIONS_REQUEST",
  ADD_DESCRIPTIONS_RESPONSE = "ADD_DESCRIPTIONS_RESPONSE",
}

export default ActionTypes;
