enum ActionTypes {
    LOGIN_REQUEST='LOGIN_REQUEST',
    LOGIN_RESPONSE='LOGIN_RESPONSE',
    LOGIN_ERROR='LOGIN_ERROR',
    FETCH_STATES='FETCH_STATES',
    CLEAR_STATES='CLEAR_STATES',
    REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST',
    REFRESH_TOKEN_RESPONSE = 'REFRESH_TOKEN_RESPONSE',
  }
  
  export default ActionTypes;