enum ActionTypes {
    AMOULET_CREATE_REQUEST = 'AMOULET_CREATE_REQUEST',
    AMOULET_CREATE_RESPONSE = 'AMOULET_CREATE_RESPONSE',
    AMOULET_GIVER_CODE_REQUEST = 'AMOULET_GIVER_CODE_REQUEST',
    AMOULET_GIVER_CODE_RESPONSE = 'AMOULET_GIVER_CODE_RESPONSE',
    AMOULET_RECEIVER_CODE_REQUEST = 'AMOULET_RECEIVER_CODE_REQUEST',
    AMOULET_RECEIVER_CODE_RESPONSE = 'AMOULET_RECEIVER_CODE_RESPONSE',
}
  
export default ActionTypes;