enum ActionTypes {
  TOKEN_VERIFICATION_REQUEST='TOKEN_VERIFICATION_REQUEST',
  TOKEN_VERIFICATION_RESPONSE='TOKEN_VERIFICATION_RESPONSE',
  ENABLE_USER_REQUEST='ENABLE_USER_REQUEST',
  ENABLE_USER_RESPONSE='ENABLE_USER_RESPONSE',
  }
  
  export default ActionTypes;