enum ActionTypes {
    GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST',
    GET_ORDER_DETAILS_RESPONSE = 'GET_ORDER_DETAILS_RESPONSE',
    LINK_AMOULET_REQUEST = 'LINK_AMOULET_REQUEST',
    LINK_AMOULET_RESPONSE = 'LINK_AMOULET_RESPONSE',
}

export default ActionTypes;