enum ActionTypes {
    ADD_ITEM='ADD_ITEM',
    USER_LIST_REQUEST='USER_LIST_REQUEST',
    USER_LIST_RESPONSE='USER_LIST_RESPONSE',
    GEN_CONFIG_REQUEST='GEN_CONFIG_REQUEST',
    GEN_CONFIG_RESPONSE='GEN_CONFIG_RESPONSE',
    AMOULET_LIST_REQUEST = 'AMOULET_LIST_REQUEST',
    AMOULET_LIST_RESPONSE = 'AMOULET_LIST_RESPONSE',
  }
  
  export default ActionTypes;